baseURL: "https://borgmon.github.io/"
languageCode: "en-us"
title: "Borgmon Me"
theme: hugo-profile
relativeURLs: true

Paginate: 6
markup:
  goldmark:
    renderer:
      unsafe: true

Menus:
  main:
    - identifier: project
      name: Projects
      title: Projects
      url: /projects
      weight: 1
    - identifier: tag
      name: Tags
      title: Tags
      url: /tags
      weight: 1

params:
  title: "Borgmon Me"
  description: Borgmon Me personal site
  favicon: "/fav.png"

  theme:
    disableThemeToggle: false
    # defaultTheme: "light" # dark

  # font:
  #   fontSize: 1.5rem # default: 1rem
  #   fontWeight: 500 # default: 400
  #   lineHeight: 1 # default: 1.5
  #   textAlign: right # default: left

  # color preference
  color:
    textColor:
    secondaryTextColor:
    backgroundColor:
    secondaryBackgroundColor:
    primaryColor: "#FF7568"
    secondaryColor:

    darkmode:
      textColor:
      secondaryTextColor:
      backgroundColor:
      secondaryBackgroundColor:
      primaryColor: "#FF7568"
      secondaryColor:

  # If you want to customize the menu, you can change it here
  navbar:
    #   align: mx-auto # Left: ms-auto | center: mx-auto | right: me-auto | Default: ms-auto
    #   brandLogo: "/logo.png" # Logo for the brand | default is the favicon variable
    #   brandName: "Profile" # Brand name for the brand | default is the title variable

    menus:
      # disableAbout: true
      disableExperience: true
      disableEducation: true
      disableProjects: true
      disableAchievements: true
      # disableContact: true

  # Hero
  hero:
    enable: true
    intro: "Hi, my name is"
    title: "Borgmon."
    subtitle: "I build scalable things"
    content: "A full stack developer also do something else: VR/AR, ML, SRE."
    socialLinks:
      fontAwesomeIcons:
        - icon: fab fa-github
          url: https://github.com/borgmon

  # About
  about:
    enable: true
    title: "About Me"
    content: |-
      I am Borgmon. A full stack developer. I enjoy creating data flow. From front-end to backend, through load balancer, they are transformed via immutable stream and saved to database. They are bouncing bits, they can be traced, be visualized, and be studied. 

      I’m looking forward to engineer on those bouncing bits for your business.
    skills:
      enable: true
      title: "Here are a few technologies I've been working with recently:"
      items:
        - "Go"
        - "Next.js"
        - "Scala"
        - "Unity"
        - "Pytorch"
        - "Docker"

  # projects
  projects:
    enable: true
    items:

  #Contact
  contact:
    enable: true
    emailImage: ./images/email.jpg
    btnName: Mail me

  footer:
    recentPosts: false
    socialNetworks:
      github: https://github.com/borgmon
